//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 10:00:25 AM BRST 
//


package br.inf.portalfiscal.nfe.canc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.nfe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CancNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "cancNFe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.nfe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TCancNFe.InfCanc }
     * 
     */
    public TCancNFe.InfCanc createTCancNFeInfCanc() {
        return new TCancNFe.InfCanc();
    }

    /**
     * Create an instance of {@link TProcCancNFe }
     * 
     */
    public TProcCancNFe createTProcCancNFe() {
        return new TProcCancNFe();
    }

    /**
     * Create an instance of {@link TRetCancNFe.InfCanc }
     * 
     */
    public TRetCancNFe.InfCanc createTRetCancNFeInfCanc() {
        return new TRetCancNFe.InfCanc();
    }

    /**
     * Create an instance of {@link TCancNFe }
     * 
     */
    public TCancNFe createTCancNFe() {
        return new TCancNFe();
    }

    /**
     * Create an instance of {@link TRetCancNFe }
     * 
     */
    public TRetCancNFe createTRetCancNFe() {
        return new TRetCancNFe();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCancNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "cancNFe")
    public JAXBElement<TCancNFe> createCancNFe(TCancNFe value) {
        return new JAXBElement<TCancNFe>(_CancNFe_QNAME, TCancNFe.class, null, value);
    }

}
